spring.application.name=spring-boot-crud-operations

spring.datasource.url= jdbc:postgresql://localhost:5432/libraryDB
spring.datasource.username=postgres
spring.datasource.password=Revanth@945

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect